version: "3.9"

services:
  # Edge Layer
  traefik:
    image: docker.arvancloud.ir/traefik:v3.6.7
    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yml

    networks:
      - traefik-public
      - monitoring

    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      mode: replicated
      replicas: 1

      placement:
        constraints:
          - node.role == manager

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s

      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.example.com`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.routers.traefik.service=api@internal
        # API dashboard is internal; no loadbalancer port label needed


  # Application Layer
  frontend:
    image: frontend:1.0.4

    networks:
      - traefik-public
      - frontend
      - backend

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/health >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1
      placement:
        preferences:
          - spread: node.id

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s

      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.http.routers.frontend.rule=Host(`shopstream.example.com`)
        - traefik.http.routers.frontend.entrypoints=web
        - traefik.http.services.frontend.loadbalancer.server.port=80


  api-gateway:
    image: api-gateway:1.0.1

    networks:
      - traefik-public
      - backend
      - data

    environment:
      PORT: "3000"
      NODE_ENV: "production"

      REDIS_HOST: "shopstream_redis"
      REDIS_PORT: "6379"

      # Use real Swarm service names (stack-prefixed) to avoid DNS/alias issues
      AUTH_SERVICE_URL: "http://shopstream_auth-service:5000"
      PRODUCT_SERVICE_URL: "http://shopstream_product-service:3000"
      ORDER_SERVICE_URL: "http://shopstream_order-service:5000"
      NOTIFICATION_SERVICE_URL: "http://shopstream_notification-service:3000"

    secrets:
      - jwt_secret
      - redis_password

    command:
      - /bin/sh
      - -c
      - |
        export JWT_SECRET="$$(cat /run/secrets/jwt_secret)"
        export REDIS_PASSWORD="$$(tr -d '\r\n' < /run/secrets/redis_password)"
        exec node src/index.js

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1

      placement:
        preferences:
          - spread: node.id

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s

      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public

        # Route /api on the SAME host as the frontend
        - traefik.http.routers.api.rule=Host(`shopstream.example.com`) && PathPrefix(`/api`)
        - traefik.http.routers.api.entrypoints=web
        - traefik.http.routers.api.priority=100

        # Strip /api before forwarding to gateway
        - traefik.http.middlewares.api-strip.stripprefix.prefixes=/api
        - traefik.http.routers.api.middlewares=api-strip
        - traefik.http.services.api.loadbalancer.server.port=3000


  auth-service:
    image: auth-service:1.0.1

    networks:
      - backend
      - data

    environment:
      PORT: "5000"
      TOKEN_EXPIRY_HOURS: "24"

      # IMPORTANT: Swarm DNS is the SERVICE NAME (stack-prefixed)
      DB_HOST: "shopstream_mariadb"
      DB_PORT: "3306"
      DB_NAME: "shopstream"
      DB_USER: "shopstream"

    secrets:
      - jwt_secret
      - db_password

    command:
      - /bin/sh
      - -c
      - |
        export JWT_SECRET="$$(cat /run/secrets/jwt_secret)"
        export DB_PASSWORD="$$(tr -d '\r\n' < /run/secrets/db_password)"
        exec python app.py

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1

      placement:
        preferences:
          - spread: node.id

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s


  product-service:
    image: product-service:1.0.0

    networks:
      - backend
      - data

    environment:
      PORT: "3000"
      NODE_ENV: "production"

      DB_HOST: "shopstream_mariadb"
      DB_PORT: "3306"
      DB_NAME: "shopstream"
      DB_USER: "shopstream"

      # Use service name
      ELASTICSEARCH_URL: "http://shopstream_elasticsearch:9200"

    secrets:
      - db_password
      - elasticsearch_password

    command:
      - /bin/sh
      - -c
      - |
        export DB_PASSWORD="$$(tr -d '\r\n' < /run/secrets/db_password)"
        export ELASTICSEARCH_PASSWORD="$$(tr -d '\r\n' < /run/secrets/elasticsearch_password)"
        exec node src/index.js

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1

      placement:
        preferences:
          - spread: node.id

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s


  order-service:
    image: order-service:1.0.0

    networks:
      - backend
      - data

    environment:
      PORT: "5000"

      DB_HOST: "shopstream_mariadb"
      DB_PORT: "3306"
      DB_NAME: "shopstream"
      DB_USER: "shopstream"

      RABBITMQ_HOST: "shopstream_rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "shopstream"

      PRODUCT_SERVICE_URL: "http://shopstream_product-service:3000"

    secrets:
      - db_password
      - rabbitmq_password

    command:
      - /bin/sh
      - -c
      - |
        export DB_PASSWORD="$$(tr -d '\r\n' < /run/secrets/db_password)"
        export RABBITMQ_PASSWORD="$$(tr -d '\r\n' < /run/secrets/rabbitmq_password)"
        exec python app.py

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1

      placement:
        preferences:
          - spread: node.id

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s


  notification-service:
    image: notification-service:1.0.1

    networks:
      - traefik-public
      - backend
      - data

    environment:
      PORT: "3000"
      NODE_ENV: "production"
      RABBITMQ_HOST: "shopstream_rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "shopstream"
      RABBITMQ_PASSWORD_FILE: "/run/secrets/rabbitmq_password"

    secrets:
      - rabbitmq_password

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    deploy:
      replicas: 1

      placement:
        preferences:
          - spread: node.id

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      update_config:
        parallelism: 1
        delay: 30s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.1
        order: start-first

      rollback_config:
        parallelism: 1
        delay: 10s

      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.http.routers.ws.rule=Host(`ws.example.com`)
        - traefik.http.routers.ws.entrypoints=web
        - traefik.http.services.ws.loadbalancer.server.port=3000


  # Data Layer
  mariadb:
    image: mariadb:11.8
    networks:
      - data

    volumes:
      - mariadb-data:/var/lib/mysql

    secrets:
      - db_password
      - db_root_password

    configs:
      - source: mariadb-init-sql
        target: /docker-entrypoint-initdb.d/init.sql
        uid: "999"
        gid: "999"
        mode: 0444

    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      MARIADB_DATABASE: shopstream
      MARIADB_USER: shopstream
      MARIADB_AUTO_UPGRADE: "1"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.db == true

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

    healthcheck:
      test: ["CMD", "sh", "-c", "pidof mariadbd || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s


  redis:
    image: docker.arvancloud.ir/redis:8.4-alpine
    networks:
      - data
    volumes:
      - redis-data:/data
    secrets:
      - redis_password

    command:
      - sh
      - -ec
      - |
        PASS="$$(tr -d '\r\n' < /run/secrets/redis_password)"
        exec redis-server \
          --appendonly yes \
          --requirepass "$$PASS"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

    healthcheck:
      test: ["CMD-SHELL", "PASS=$$(tr -d '\r\n' < /run/secrets/redis_password); redis-cli -a \"$$PASS\" ping | grep -q PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


  rabbitmq:
    image: docker.arvancloud.ir/rabbitmq:4.2-management
    networks:
      - data

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia

    secrets:
      - rabbitmq_password

    environment:
      RABBITMQ_DEFAULT_USER: shopstream

    entrypoint:
      - /bin/sh
      - -ec
      - |
        export RABBITMQ_DEFAULT_PASS="$$(tr -d '\r\n' < /run/secrets/rabbitmq_password)"
        exec docker-entrypoint.sh rabbitmq-server

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s


  minio:
    image: docker.arvancloud.ir/minio/minio:RELEASE.2025-09-07T16-13-09Z

    networks:
      - data

    volumes:
      - minio-data:/data

    secrets:
      - minio_access_key
      - minio_secret_key

    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_access_key
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_secret_key
      MINIO_BROWSER: "on"

    command: server /data --console-address ":9001"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s


  elasticsearch:
    image: docker.arvancloud.ir/elasticsearch:9.2.4

    networks:
      - data

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - node.name=es01

    ulimits:
      memlock:
        soft: -1
        hard: -1

    deploy:
      placement:
        constraints:
          - node.role == manager

      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M

      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s


networks:
  traefik-public:
    external: true
  monitoring:
    external: true
  frontend:
    external: true
  backend:
    external: true
  data:
    external: true


volumes:
  mariadb-data:
  redis-data:
  rabbitmq-data:
  minio-data:
  elasticsearch-data:


secrets:
  db_root_password:
    external: true
  db_password:
    external: true
  redis_password:
    external: true
  jwt_secret:
    external: true
  rabbitmq_password:
    external: true
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
  elasticsearch_password:
    external: true


configs:
  mariadb-init-sql:
    external: true
  traefik_config:
    external: true
